Repository suryanshsk/Python-Voice-Assistant-Suryanshsk, pull requests merged in 2024-10, with the labels that each got.

#50 Added new features to the "news" file
  news_info.py
Labels: gssoc-ext, hacktoberfest-accepted, level3

#87 Added a language translation feature
  README.md
  language_translator.py
Labels: gssoc-ext, hacktoberfest-accepted, level2

#82 Added the codes for storyteller and recipe book with a readme file
  Recipe-book/Recipes.py
  Recipe-book/readme.md
  Storyteller/Readme.md
  Storyteller/Storytime.py
Labels: gssoc-ext, hacktoberfest-accepted, level3

#83 Navbarchange
  frontend/index.html
  frontend/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level3

#91 Added GUI for Voice Assistant and sound wave display
  gui_assistant.py
  sound_wave.png
Labels: gssoc-ext, hacktoberfest-accepted, level3

#139 Added Face detector to the assisstant
  face_detector.py
Labels: gssoc-ext, hacktoberfest-accepted, level2

#138 voice recognition
  README.md
  voice_recognition.py
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#324 Create Gesture Recognition using CNN.py
  Gesture Recognition using CNN.py
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#327 Added Privacy features
  Secure data/Private.py
  Secure data/Readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#441 Added the emotional charades games
  emotional_charades.py
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest
